

date=$(shell date)

n_lines=$(shell wc -l < guessinggame.sh)

README.md: guessinggame.sh
	echo "Title: Project " > README.md
	echo "Date: $(date)  " >> README.md
	echo "Number of lines \`guessinggame.sh\`: $(n_lines)  " >> README.md
